### ISSUE TITLE
[question] does this require Terraform Cloud? 

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-k8s#84]
I dont use terraform cloud I just have my state for all my workspaces in s3

Do I _have_ to create a terraform cloud account in order to use this operator?

**Comment by redeux** [comment]
Hi @red8888, thanks for the question.  We're tracking support for an Operator based on Terraform OSS in #10.  

We built this operator around a workflow with Terraform Cloud. We opted to go this route for now because we believe the Terraform Cloud features around team based workflows and governance pair well with the primary use cases we see among Kubernetes users.

I understand that there will always be folks that want a HashiCorp support version using Terraform OSS, and we remain open to the possibility, but there are no active plans to address this use case.

I’m going to close this issue for now, but if you have more to add, I encourage you to continue to conversation in #10.
